{
  "id": "PYSEC-2023-6",
  "details": "Improper Authentication vulnerability in Apache Software Foundation Apache IoTDB.This issue affects Apache IoTDB: from 0.13.0 before 0.13.3.",
  "aliases": [
    "CVE-2023-24830"
  ],
  "modified": "2023-05-04T03:49:44.840128Z",
  "published": "2023-01-30T17:15:00Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://lists.apache.org/thread/l4fon37687jz5ohgsnz2ko9fv400915t"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "apache-iotdb",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/apache-iotdb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0.13.0"
            },
            {
              "fixed": "0.13.3"
            }
          ]
        }
      ],
      "versions": [
        "0.13.0",
        "0.13.0.post1",
        "0.13.1",
        "0.13.2"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/apache-iotdb/PYSEC-2023-6.yaml"
      }
    }
  ],
  "schema_version": "1.4.0"
}